### ISSUE TITLE
Holy shit thank you for working on this

### ISSUE THREAD

**Issue by Cruplezone** [cotodevel/SnemulDS#3]
Sorry, don't know how to comment other than create an issue. Is it possible to get a release zip on for this project? I would love to see this emulator reach accurate levels of gameplay, do you think that would ever be possible? also gbatemp link?

**Comment by cotodevel** [comment]
Thanks! I will add a release folder with a precompiled .nds file. It will be called releases.Initially I thought that would be a bad idea, but then, some people just don´t care about compiling, but rather just test/play.

Also if you want a zip of teh source code you can always perform these steps:

Click any commit number>browse files>Clone or Download

About the accurate levels of gameplay, I am slowly replacing SNESIRQs for something updated
up to today snes emu cores standards ,and they seem to work, but co processors and such require to have replaced SNES CPU Core opcodes. Before that happens i would say, snemulDS is enough accurate for simpler games, but not for co processor games.

**Comment by Cruplezone** [comment]
Do you have a rough idea of when the first release will be?

**Comment by Cruplezone** [comment]
Alright finally got around to building it myself! Runs playable for sure, but seems faster than the actual games. For sure alpha layers need working on like you posted in the to-do and also the music is definitely jittery. Overall those were my biggest gripes with the games I tried (painful to listen to music, invisible layers not working, games running too fast). Hopefully you can look into that stuff when you've got time :)

**Comment by cotodevel** [comment]
I am writing custom IRQs for the NDS system, that must be used between this & the other projects. I won´t add new features to anything if I dont fix those. 

Namely:
- IRQs 
- Wifi 
- FIFO (these work just fine but LIBNDS IRQ library rely on LIBNDS core functions), while the ones I am coding rely more on the hardware (it really makes a difference when you read from hardware registers to wait for FIFO interrupts, against the slower FIFO messages queue ). More on that below:

There is no point to use a library that works in a project, then you want to use the same against another one, and it breaks because the other project used them vastly different. (namely, projects that use NDS hardware in a way LIBNDS maintainers do not support)

For example snemulDS uses wait for vblank for almost everything (slow), and that breaks DSNIFI. Since DSNIFI is expected at certain point for BOTH ARM Cores to sync at wait for vblank , it lead to weird glitches such as not connecting to AP or skipping cycles.

Other projects such as gbaemu4ds has a custom (bios @ 0x00000000) and the default swi bios call wait for vblank does not work, since the bios is trapped by MPU , and the fallback bios handler calls a CP15 (coprocessor call) wait for vblank, but cause issues and does not cause the same effect as calling any normal NDS program (bios @0xffff0000). This affect any library that works for libnds, but for custom projects , it does not work.

So once I have this library ready, it should be updated across all the projects. And then I would even consider adding new features...

**Comment by Cruplezone** [comment]
Sounds great! Makes sense honestly, wouldn't expect features with a major rewrite like that. I'd just like to say I really appreciate your work on this and hope you continue with it, your emulators are second to none and I use this and nesDS extensively! Love them both.

**Comment by cotodevel** [comment]
Yeah the star button (*) and closing the lid must be fixed.. Those used ancient code that I believe was not fully standard at the time by LIBNDS devs. So I will simply remove it if I don't see any use for it.. but I guess Archeide added it for some reason..

I am well aware of gbarunner2. I posted RTC support since I added it to gbaemu4ds (not released) long ago:  http://gbatemp.net/threads/gbarunner2.451970/#post-6902997

**Comment by batoussai** [comment]
I wanted to try implementing sleep mode, one that works, since I'd appreciate having this function. But I'm either having a brain fart or master doesn't compile while experimental compiles but crashes (on my R4). Can anyone confirm?
