### ISSUE TITLE
ARM 9: DATA ABORT

### ISSUE THREAD

**Issue by Boured** [cotodevel/SnemulDS#5]
Recently was able to compile this due to me being able to read things and use my brain. Though when starting it from my R4 it loads the first screen before crashing to [this](https://cdn.discordapp.com/attachments/213903947935645696/384173939221594122/JPEG_20171125_194945.jpg). Was wondering if this is because the source is still being updated and it's currently in a state where it can't work right now but I wanted to hear it from you. Not to mention this seems to be the only way to contact you. 

Hope you can help, thank you :)

**Comment by cotodevel** [comment]
Thank you for your interest in ToolchainGenericDS, only good stuff is about to arrive! 
If you ever want to ask something this is the perfect channel.

Yeah, I decided to push the newlib nano for NintendoDS rewrite, as the older still used parts from the GNU toolchain, and while it didn't cause problems, .NDS binary filesizes were affected.

Currently I just pushed re-malloc in newlib nano support, working fine. So that's one bug less 

The data aborts are due to other newlib nano specific parts that are being excluded, asap I fix those bugs I will reply here

**Comment by cotodevel** [comment]
All right. 

Please remove all traces of ToolchainGenericDS setup:
-  Go to c:/ and delete /toolchain_generic folder
-  Then perform a fresh git checkout/ download latest sources from:

-newlib-nano-2 -> newlibnano2.1-nds branch
-ToolchainGenericDS -> master branch
-SnemulDS -> master branch

And recompile, tell me if it works now. 


Specifics:
I got it to work. If someone is interested as why did this happen here is a small write-up:

Earlier ToolchainGenericDS used a GNU toolchain to link newlib parts, including posix fs. The problem was I just linked everything there. That meant literally patching newlib code, but the bottom point of newlib was to rebuild everything rather than patch. Since I didn't do that most API stuff would behave somewhat not correctly.

So, that led me to adapt a newlib nano, so it generates an output linkable format, compatible to work with ToolchainGenericDS, recompiled 100% for the NintendoDS processor.

**Comment by Boured** [comment]
It compiled and ran, though it might need some work as the emulator is pretty blarg. Though that isn't your fault. The original was just a bad if I remember correctly. I did notice it ran much better than the old one.

But yeah thanks for the help :3

**Comment by cotodevel** [comment]
"It isn't your fault" . Well if you want to submit pull requests I am waiting. Closing issue.
