### ISSUE TITLE
Add compatibility with DSi Mode 🌞

### ISSUE THREAD

**Issue by WodsonKun** [cotodevel/SnemulDS#6]
SNEmulDS (actually) don't work on DSi (SD Slot)
Maybe, if you add support to it... 😄

**Comment by cotodevel** [comment]
The DSi uses a different map (non NTR). ToolchainGenericDS projects support NTR map only.
In fact, I plan to add everything to DS (NTR) modes, even if it's more difficult due to lower RAM/CPU
(in fact it is not, just look at Gameboy hardware, or why not a calculator to create games, like Iwata-san would). That sole reason leads me to believe there is no need for DSi mode when DS mode can do a lot.


Now, if someone wants to help, and wants to extend ToolchainGenericDS projects so they build valid DSi homebrew, then the parts required would be:

- gnu gplv2 (or higher) compatible license

- A valid DSi header parser (that takes ARM7i and ARM9i binaries and creates a valid header for DSi mode, so the binary runs in TWL mode) 

- has coding skills so he/she must turn NTR mode TGDS linkers into TWL mode linkers. I could help there if necessary.

- has coding skills to add the hardware parts that are different in TWL mode:
   such as: new DMAs, IC, DSi Wifi mode, Touchscreen

I know devkitpro exists as an alternative but all TGDS code has its own license. And their license is not GPL compatible.


... or simply get a slot-1 device that runs NTR homebrew.
